[[cells]]
name = "bonding-curve-lock.bc"
enable_type_id = true

  [cells.location]
  file = "/Users/retric/Desktop/simple-bonding-curve/packages/bonding-curve/dist/bonding-curve-lock.bc"

[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x758d311c8483e0602dfad7b69d9053e3f917457d"
hash_type = "type"
